Repository dnd-side-project/dnd-12th-2-backend, pull requests merged in 2025-03, with the labels that each got.

#33 [BUG] Expried Jwt Token with Wrong Exception
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/core/config/WebConfig.java
  src/main/java/ac/dnd/dodal/core/security/JwtAuthEntryPoint.java
  src/main/java/ac/dnd/dodal/core/security/config/SecurityConfig.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtExceptionFilter.java
  src/main/resources/db/migration/V20__update_sample_refresh_token.sql
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/auth/refreshAccessTokenAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/onboarding/GetOnBoardingDataAcceptanceTest.java
  src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
  src/test/java/ac/dnd/dodal/core/security/util/JwtUtilTest.java
Labels: PR 🚀 WILL CLOSE, Priority !! HIGH, Type 🪰 BUG FIX

#39 Refactor/optimal deploy
  .github/workflows/OriginRepoCD.yml
  Dockerfile
Labels: PR 🚀 WILL CLOSE, Type 🔨 REFACTOR

#38 [FEAT] User 탈퇴 기능 구현
  src/main/java/ac/dnd/dodal/application/user/repository/UserRepository.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthService.java
  src/main/java/ac/dnd/dodal/application/user/service/UserCommandService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/UserCommandUseCase.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/ac/dnd/dodal/core/security/provider/JwtAuthenticationProvider.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
  src/main/java/ac/dnd/dodal/ui/auth/AuthController.java
  src/main/java/ac/dnd/dodal/ui/auth/response/UserInfoResponseDto.java
  src/test/java/ac/dnd/dodal/acceptance/auth/steps/AuthSteps.java
  src/test/java/ac/dnd/dodal/acceptance/auth/withdrawUserAcceptanceTest.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE
